PROMPT 1 — Hero Section
"Create a professional, corporate-grade hero section for Devisor, an industry planning firm. Use #EB0707 for accent buttons and micro-details, #FFFFFF as the primary background, and #3C4044 for text elements. Typography is exclusively Poppins (Bold for headings, Medium for subheadings, Regular for body). The hero layout splits into two columns: left side holds the headline, a one-line subtext describing Devisor's planning expertise, and two CTA buttons (primary in #EB0707 with white label, secondary as outlined in #3C4044). The right side holds a full-height professional image that is diagonally sliced — the cut runs from slightly left-of-center at the top to slightly right-of-center at the bottom, creating a dynamic angular crop that bleeds into the section. Add a sticky navigation bar in #FFFFFF with the Devisor logo left-aligned, nav links center or right-aligned in Poppins Medium, and the primary CTA button in #EB0707. On hover, nav links underline in #EB0707 with a 200ms ease transition. On scroll past the hero, the navbar gains a soft box-shadow. Hero text and buttons animate in with fade-from-bottom on page load, staggered 100ms per element. Responsive: at 768px the layout stacks vertically, image moves below text, diagonal slice becomes a bottom-edge angle cut; at 375px image scales to 60% height and buttons stack full-width."

PROMPT 2 — Interactive Feature Grid
"Create a professional feature grid section for Devisor on a #3C4044 dark background with #FFFFFF text and #EB0707 icon accents. Typography is Poppins throughout. The section opens with a centered section title ('Why Devisor') in Poppins Bold and a short descriptor line in Poppins Regular. Below, display a 3-column grid of feature cards (6 cards total), each containing: an #EB0707 icon or geometric symbol, a short feature title in Poppins SemiBold, and a 2-line description in Poppins Regular. Card background is slightly lighter than the section (#4A5055 or a subtle elevated tone), with 16px border-radius and 24px inner padding. Hover behavior: cards lift with a 4px translateY, border-left becomes a 3px solid #EB0707 stroke, and a subtle white glow appears — all transitions at 250ms ease-in-out. Cards enter the viewport with staggered fade-from-bottom animations, 80ms delay between each card. Responsive: 2 columns at 768px, 1 column at 375px, each card full-width."

PROMPT 3 — What We Offer Block (3 Services)
"Create a 'What We Offer' section for Devisor on a #FFFFFF background with #3C4044 text and #EB0707 highlights. Typography is Poppins exclusively. Section title 'What We Offer' centered in Poppins Bold 36px, with a short introductory sentence beneath in Regular. Display 3 service cards in a horizontal row, each structured as: a large #EB0707 number or icon at the top, bold service title in Poppins SemiBold, a 3–4 line description in Regular, and a text-link CTA ('Learn More →') in #EB0707 that underlines on hover. Cards have a clean white base with a bottom-border accent in #EB0707 that expands full-width on hover (width transitions from 0 to 100% over 300ms). Each card has a very subtle #3C4044 drop shadow that deepens on hover. The entire section fades in from the bottom as the user scrolls into view. Responsive: cards stack to a single column at 768px and below, maintaining the bottom-border hover effect and full-width CTA link."

PROMPT 4 — Service Detail Expansion Block
"Create a service deep-dive section for Devisor that follows the 'What We Offer' block. Background alternates: first service block uses #FFFFFF, second uses #3C4044, third returns to #FFFFFF — creating a visual rhythm. Typography is Poppins throughout; on dark blocks use #FFFFFF text, on light blocks use #3C4044. Each of the 3 service blocks is a two-column layout: one column holds a large contextual image or illustration (with the same diagonal-slice framing style used in the hero), the other holds the service title in Poppins Bold, 4–5 bullet points of deliverables in Poppins Regular with #EB0707 bullet markers, and a solid #EB0707 CTA button. Alternate image-left and image-right layout per block to create visual flow. Hover on CTA button: slight scale(1.03) and brightness increase, 200ms ease. Scroll behavior: each block fades in from the bottom as it enters the viewport, with the image and text animating in from opposite sides (image from left, text from right — or vice versa). Responsive: at 768px, each block stacks to single column with image on top, text below; at 375px image height is constrained to 220px."

PROMPT 5 — Conversion CTA Block + Structured Footer
"Create a conversion-focused CTA block immediately followed by a structured footer for Devisor. The CTA block uses a #EB0707 full-width background with centered white text: a bold Poppins headline ('Ready to Plan Smarter?'), a single supporting line in Poppins Regular, and one large white button with #EB0707 text label ('Get In Touch'). On hover, the button inverts: #EB0707 background with white text, 250ms ease transition. The block fades in from bottom on scroll entry. The footer sits on #3C4044 background with #FFFFFF text and #EB0707 link hovers. Structure the footer in a 4-column layout: Column 1 — Devisor logo + one-line brand description in Poppins Light; Column 2 — 'Services' nav links in Poppins Regular; Column 3 — 'Company' links (About, Careers, Contact); Column 4 — Contact details (email, phone, address) with social media icons in #FFFFFF that turn #EB0707 on hover. A thin #EB0707 divider line separates the footer body from a bottom bar containing copyright text in Poppins Light 12px. All footer links have a 150ms color-fade hover transition. Responsive: footer collapses to 2 columns at 768px and 1 stacked column at 375px, with the CTA block maintaining full-width at all breakpoints."